title:             Dirk Eilander
email:             dirk.eilander@gmail.com
description:       Hydrologist
author:            Dirk Eilander
baseurl:           ""
url:               "http://DirkEilander.github.io"

# Social Profiles
twitter_username:  DirkEilander
github_username:   DirkEilander

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
